# Generated by Django 4.1.2 on 2022-10-19 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("boraApp", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="agendamento",
            old_name="localidade",
            new_name="quadra",
        ),
    ]
