# Generated by Django 4.1.1 on 2022-10-20 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boraApp', '0002_rename_localidade_agendamento_quadra'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agendamento',
            name='inicio',
            field=models.TimeField(),
        ),
    ]
